name: Node CI
run-name: ${{ github.actor }} is running node CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Load Node.js version with NVM
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
